import fs from 'fs'
import path from 'path'

const PDF_DIR = path.resolve(__dirname, '../public/pdfs/stories')
const COVERS_DIR = path.resolve(__dirname, '../public/images/covers')
const OUTPUT_FILE = path.resolve(__dirname, '../src/data/generated-stories.ts')

function slugToTitle(slug: string): string {
  return slug
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function parsePdfFilename(filename: string) {
  const basename = filename.replace(/\.pdf$/i, '')
  const date = basename.slice(0, 10)
  const slug = basename.slice(11)
  const title = slugToTitle(slug)
  return { date, slug, title }
}

function findCoverImage(slug: string, date: string): string {
  const coverFilename = `${date}-${slug}.png`
  const coverPath = path.join(COVERS_DIR, coverFilename)

  if (fs.existsSync(coverPath)) {
    return `/images/covers/${coverFilename}`
  }
  return '/images/covers/default-cover.png'
}

function generate() {
  if (!fs.existsSync(PDF_DIR)) {
    fs.mkdirSync(PDF_DIR, { recursive: true })
  }

  const files = fs
    .readdirSync(PDF_DIR)
    .filter((f) => f.toLowerCase().endsWith('.pdf'))
    .sort()
    .reverse()

  const stories = files.map((filename, index) => {
    const { date, slug, title } = parsePdfFilename(filename)
    const coverImage = findCoverImage(slug, date)
    const pdfUrl = `/pdfs/stories/${filename}`

    return {
      id: `pdf-${index + 1}`,
      slug,
      title,
      date,
      category: 'english-book' as const,
      tags: ['英文绘本', '亲子阅读'],
      ageRange: '4-8岁',
      duration: '8分钟',
      coverImage,
      pdfUrl,
      description: `今天和优米Leo一起阅读《${title}》，每天15分钟，讲故事、读绘本、看世界。`,
    }
  })

  const output = `// This file is auto-generated by scripts/generate-pdf-index.ts
// Do not edit manually. Run: npm run generate:stories

export type StoryCategory =
  | 'english-book'
  | 'chinese-story'
  | 'world-culture'
  | 'music'
  | 'daily-life'

export type Story = {
  id: string
  slug: string
  title: string
  date: string
  category: StoryCategory
  tags: string[]
  ageRange: string
  duration: string
  coverImage: string
  pdfUrl: string
  description: string
  goal?: string
  vocabulary?: {
    word: string
    meaning: string
    example?: string
  }[]
  parentQuestions?: string[]
}

export const generatedStories: Story[] = ${JSON.stringify(stories, null, 2)}
`

  const outputDir = path.dirname(OUTPUT_FILE)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8')
  console.log(`✅ Generated ${stories.length} stories → ${OUTPUT_FILE}`)
}

generate()
